default: &default
  adapter: postgresql
  encoding: unicode
  database: recipe_app_development
  pool: 5
  username: postgres
  password: kingno3l
  host: localhost
  port: 5433

development:
  <<: *default
  database: recipe_app_development

test:
  <<: *default
  database: recipe_app_test


production:
  <<: *default
  database: recipe_app_production
  username: postgres
  password: kingno3l
