
default: &default
  adapter: postgresql
  encoding: unicode
  database: recipe_development
  pool: 5
  username: postgres
  password: kingno3l
  host: localhost
  port: 5433

development:
  <<: *default
  database: recipe_development

test:
  <<: *default
  database: recipe_test

production:
  <<: *default
  database: recipe_production
  username: postgres
  password: kingno3l
